const citiess = {
    Bangalore: [
      "Whitefield",
      "Marathahalli",
      "Silk Board",
      "Sarajpur",
      "AECS Layout",
      "Kundalahalli",
      "Varthur",
      "Hope Farm",
      "ITPL",
      "Brookfield",
      "Shantiniketan",
      "Hoodi",
      "MunneKolala",
      "Doddanekundi",
      "Mahadevpura",
      "KR Puram",
      "Kadubeesanahalli",
      "Thippasandra",
      "Murugeshpalya",
      "HAL Road",
      "Bagmane Tech Park",
      "Electronic City",
      "Bommanahalli",
      "Tavarekere",
      "Axa Building",
      "Kudlu Gate",
      "Bommasandra",
      "Madiwala",
      "Nagawara",
      "Hebbal",
      "Hennur Road",
      "HBR layout",
      "Banaswadi",
      "Manyata Tech Park",
      "Thanisandra",
      "Koramangala",
      "Domlur",
      "Indiranagar",
      "MG Road",
      "Ejipura",
      "Vivek Nagar",
      "Richmond Town",
      "Dairy Circle",
      "Bannerghatta road",
      "Jaya Nagar",
      "J P Nagar",
      "Wilson Garden",
      "Lal bagh",
      "Christ college",
      "Jain College",
      "Mysore Road",
      "Bellandur",
      "HSR Layout",
      "Wipro",
      "Ecospace",
      "Green Glen layout",
      "Central Mall"
    ],
    Pune: ["Ambegaon", "Hinjewadi", "Karve Nagar", "Narhe"],
    Chennai: [
      "Porur",
      "OMR",
      "Vadapalani",
      "DLF IT Park",
      "Kattupakkam",
      "Manapakkam",
      "TIDEL Park",
      "Perungudi",
      "Velachery",
      "KK Nagar",
      "Forum Vijaya Mall"
    ],
    Hyderabad: [
      "Gachibowli",
      "Kondapur",
      "Gowlidoddi",
      "Wipro Circle",
      "Financial District"
    ]
  };


  module.exports=citiess